- index.html
- js/main.js
Resolves #3 
- Moves logos to next line
- Fixes countdown timer loading issues
> Fixes countdown timer

- introductions/17co122.txt
Added my information 17CO122, Manas Gupta
a text file is there with all details required.
NA
NA
> Added details of 17CO122 Manas Gupta

- introductions/184CA013.txt
> added 184CA013 details

- introductions/182IS001.txt
Resolves Issue 36
Please explain the changes you made in detail here.
Added details for 182IS001.
NA
NA
NA
> added 182IS001 details

- introductions/181IT202.txt
added details for 181IT202
No.
No.
> added details for 181IT202

- introductions/18me178.txt
added details for 18me178
No
No
> added 18me178 details

- 17EE144.txt
Resolves Issue #36
Added details for 17EE144
NA
NA
> added 17EE144 details

- introductions/184CA028.txt
Name : Jatin Mehta
Branch : MACS 
Degree : MCA
> added 184CA028 details

- introductions/181IT153.txt.txt
ADDED PERSONAL DETAILS(181IT153).
-NA-
-NA-
> added 181I153 details

- introductions/17CO116.txt.txt
Added details for 17CO116 
NA
NA
NA
> Added 17CO116 details

- introductions/181004.txt
Resolves Issue #36
Added details of 181004 in the introductions directory.
NA
> Added 181004 details 

- introductions/17CO201.txt
Added Roll number Named  text file.
Checklist
Please explain the changes you made in detail here.
> Added details of Aashay123 17CO201

- introductions/18IT217.txt
Resolve Issues #36 
Added the details for 18IT217
NA
NA
NA
> Added details of 18IT217

- introductions/181CO111.txt
Resolves Issue #<issue_number>
Added Introduction details.
> added 181co111 details

- introductions/172CS022.txt
Resolves Issue #36
Please explain the changes you made in detail here.
Added details for 172CS022 in introduction.
NA
NA
> added rollno.txt

- algorithms/dijsktra/ashwinjoisa.c
Resolves Issue #11 
Added Dijkstra's implementation in C.
Language used: C
```
$ gcc ashwinjoisa.c
$ ./a.out
```
> Added Dijkstra

- introductions/181IT150(181276).txt
- introductions/181IT150.txt
Replaced my previous text file with another text file in another directory trial1. Updated all my personal details
NA
NA
> Resolving previous issue of no personal details

- introductions/17co122.txt
- systems/cryptography/caesar-cipher/C++
Resolves Issue #27 
this code takes lower case string as given in the issue for shift less than z it simply adds whereas when 
it goes farther than z it subtracts to give equivalent rotation
attached
enter the string and then any integer in 0-25
> changed c++ code of caesar-cipher

- algorithms/binary_search/ruby/cesar_almeida.rb
Resolves Issue #92
Created a new ruby directory in binary_search
Created a new ruby file cesar_almeida.rb
This is a simple implementation of the binary search algorithm in ruby.
First change the name of the file to binary_search.rb
You can test the algorithm on the IRB console by using irb -r ./binary_search.rb in your terminal/command prompt
OR Loading the file in your ruby code by using 
`require 'binary_search.rb'`
At the top of your ruby file.
Then just use the method binary_search
> Implemented Binary Search in Ruby

- introductions/17CO246.txt
> added intro file 

- algorithms/bubble_sort/python/brabec.py
Resolves Issue #94
I added my bubble_sort activity as algorithms/bubble_sort/python/brabec.py
Made in Python 2.7
In order to run this script correctly, just pass some arguments like this:
>$ python brabec.py 43 2 0 1 4
> Bubble Sort in Python 2.7

- algorithms/binary_search/python/v_chmykov.py
Resolves Issue #92 
Created a new python directory in binary_search
Created a new python file v_chmykov.py
This is a simple implementation of the binary search algorithm in python.
There is an example inside the file. You can just run it to test algorithm.
If you want to use it somewhere you should remove all test code (all code except 'binary_search' method) and just import method in your code.
> implement binary search in python

- systems/cryptography/rsa/C++
Resolves Issue #<29>
Please explain the changes you made in detail here.
Implemented RSA for C++
Input 2 prime numbers and a message to be encrypted.
- [x ] Code compiles correctly.
- [x ] Changes are tested properly.
- [x ] Added the README / documentation, if necessary.
- [x ] Followed the Contributing guidelines.
- [x ] Resolved merge conflicts, if any.
> C++ version of RSA Code

- machine_learning/wine_quality/rfc/wine_rfc.ipynb
Resolves Issue #33
Added random forest classifier for wine quality prediction.
> added random forest classifier for wine quality prediction

- machine_learning/iris/gnb/.ipynb_checkpoints/iris_starter_code-checkpoint.ipynb
- machine_learning/iris/gnb/README.md
- machine_learning/iris/gnb/iris_gnb.ipynb
Resolves Issue #12 
Added Gaussian Naive Bayes classifier for Iris dataset
python, scikit-learn, pandas, numpy
All output is displayed in jupyter notebook.
> Gaussian Naive Bayes classifier for Iris dataset

- systems/networks/tcp/function_call/python/README.md
- systems/networks/tcp/function_call/python/client.py
- systems/networks/tcp/function_call/python/server.py
Resolves Issue #<18>
Implemented the tcp protocol and message passing between server and client
steps written in readme
(Works in Python 2)
python server.py
python client.py
> Rajat1433 tcp

- algorithms/string_permutations/C/fedex15.c
Resolves Issue #127 
I've made a simple C algorithm to solve the problem. I had a very similar school assignment that I liked a lot so I started from that.
Simply compile the code and run it. I takes a string as the first argument.
> Permutations of a String in C

- machine_learning/wine_quality/dtc/decision-tree-wine.ipynb
Resolves Issue #33
Created  decision tree model fitted on wine red dataset. Printed accuracy score.
1.Run all lines in jupyter notebook
- [yes ] Code compiles correctly.
- [yes] Changes are tested properly.
- [comment code ] Added the README / documentation, if necessary.
- [yes] Followed the Contributing guidelines.
- [yes] Resolved merge conflicts, if any.
> Wine Decision tree

- machine_learning/wine_quality/svc/wine_svc.ipynb
Resolves Issue #33
Implemented the Support Vector Classifier solution
Run all cells in notebook
> Added SVC for wine quality prediction

- index.html
The PPT of the Session 2 has been linked to the name of the topics covered under that session.
> Updated Session 2's PPT

- machine_learning/kfolds_cross_validation/manas.py
Resolves Issue #89 
python3 manas.py IRIS.csv
> added SP file

- algorithms/binary_search/Aniket.py
- algorithms/hello_world/Python/Aniket.py
Resolves Issue #92 
Added Binary Search algorithm in Python.
Binary Search Algorithm
Move into the BinarySearch directory.
`cd algorithms/binary_search`
Execute the script:
`python Aniket.py`
> Added Binary Search algorithm in Python.

- introductions/17CO103.txt
Name: Abhinav P Y
GitHub ID: abhinavpy
Institution: NITK
Branch: Computer Science Engineering
Degree: 2nd Year, BTech
> Added 17CO103 details

- introductions/181CO145.txt
Resolves Issue #<36>
added details for 18co145
> added 18co145 details

- introductions/18CS004.txt
Resolves Issue #36
Created a file named after my roll no and filled in the details listed in issue description.
> roll no info file added

- algorithms/next_greater_number/C++/solution.cpp
Resolves Issue #13 
1.If  numbers are in descending order, print "Not possible"
2.Traverse the given number from rightmost digit, keep traversing till you find a digit which is smaller than the previously traversed digit.  If we do not find such a digit, then output is “Not Possible”.
3. Now search the right side of above found digit ‘d’ for the smallest digit greater than ‘d’.
4.Swap the above found two digits.
5.Now sort all digits from position next to ‘d’ to the end of number.And this number is output.
C++
Just enter any valid string of number and you will get the output.
> next_greater_number

- algorithms/bubble_sort/cpp/insane-abhi.cpp
Solves Issue #94 
C++ program to implement bubble sort
C++ 11
Enter no. of input N,
followed by N space/tab seperated numbers.
Results in a sorted array
Sorts in O(n^2).
> Added bubblesort.cpp by insane-abhi

- development/gradient_loader/index.css
- development/gradient_loader/index.html
Resolves Issue #199 
Add a gradient loader
Open the `index.html` file located under `development/gradient_loader` in the browser.
> Add gradient loader

- algorithms/next_greater_number/C++/solution2.cpp
Resolves Issue #13 
Added the C++ code to find the next greater number.
Language used: C++
```
$ g++ solution.cpp
$ ./a.out
```
> Solution 2, next greater element in C++

- algorithms/hello_world/Go/deepak.go
- systems/os/process_scheduling/fcfs/python/fcfs.py
Resolves Issue #16 
added algorithm for FCFS scheduling
python2 must be installed
In Linux from terminal:
Navigate to the folder ... /systems/os/process_scheduling/fcfs/python/ and execute:
python fcfs.py
> added algorithm for FCFS scheduling

- development/bash_image_search/README.md
- development/bash_image_search/image_search.sh
Resolves Issue #23 
A simple tool to visualize results from a search engine
See README.md
> bash image search added

- systems/cryptography/vigenere-cipher/java/README.md
- systems/cryptography/vigenere-cipher/java/VigenereCipher.java
Resolves Issue #208 
Implemented a solution in java
Requires Java 8 or greater
Compile with `javac VigenereCipher.java`
Run with `java VigenereChipher`
- [x ] Code compiles correctly.
- [x ] Changes are tested properly.
- [x ] Added the README / documentation, if necessary.
- [x ] Followed the Contributing guidelines.
- [x ] Resolved merge conflicts, if any.
> Added vigenere cipher for java

- systems/cryptography/vigenere-cipher/C++/c++.cpp
Resolves Issue #208
Description
Implemented the algorithm in C++.
Technical Specifications
C++
Screenshots 
Checklist
Code compiles correctly.
Changes are tested properly.
Followed the Contributing guidelines
> Added vigenere cipher in C++

- systems/cryptography/playfair-cipher/java/PlayFairCipher.java
Resolves Issue #218 
I have added a file named PlayfairCipher.java in systems/cryptography/playfair-cipher/java. This java program helps us to encrypt plain text using playfair method.
As this program is created in java, you need to have a java compiler installed to run this program.
To run this program:
1) Open your terminal
2) Go to the specific directory where the file is stored using the ''cd'' command
3) Type - javac PlayfairCipher.java
4) Type - java PlayfairCipher
5) Enter your text which is to be encrypted
6) Enter the key for encryption
7) Get the encrypted text as the output
> added program for playfair cipher

- systems/cryptography/vigenere-cipher/Python/readme.md
- systems/cryptography/vigenere-cipher/Python/vigenere.py
Resolves Issue #208 
Implemented simple vigenere cipher in Python
Python 3 required
Cipher removes all whitespaces and ignores punctuation
Run through terminal by typing
> python vigenere.py
Input plain text on first prompt
> please input plain text: 
> cryptographyisfun
Input keyword on second prompt
> please input keyword:
> idoubt
The resulting output should be shown
> Added vigenere cipher in python

- systems/cryptography/diffie-hellman/c/c.c
Resolves Issue #28
Implemented Diffie-hellman key exchange algorithm in C
Build  
```
$ gcc c.c
```
Run
```
$ ./a.out
```
> DH implemented in c

- algorithms/avl_tree/gaurivn.cpp
Resolves Issue #182 
Implementation of AVL Tree
C++
> AVL Tree in C++
